### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by rogeroffer** [C-B4/unifiedpush-server#11]
on /unifiedpush-server generates 404 error page. 

2016/02/08 19:09:30 [error] 905#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: MY-IP, server: s3.y...........r.eu, request: "GET /unifiedpush-server HTTP/1.1", upstream: "http://127.0.0.1:8080/unifiedpush-server", host: "s3.y.........r.eu"

**Comment by yaniv-cb4** [comment]
Can you provide further details:
1) OS type and version (uname -a)
2) Host type (Amazon/ESXI/...)
3) Installation logs (any log from running unifiedpush-ctl reconfigure).

**Comment by rogeroffer** [comment]
Hi,

Thanks for the quick reply. You can also login to the server, no problem.

107.6.175.175
root password: 543c583d8c


1. [root@s3 ~]# uname -a

Linux s3 2.6.32-042stab108.6 #1 SMP Thu Jul 9 13:40:24 MSK 2015 x86_64
x86_64 x86_64 GNU/Linux


2. VPS OPENVZ vmbox.co (I just ordered for one moth for test. I installed
local before with parallel desktop and was running good with same centos 7
minimal)


3.


Starting Chef Client, version 12.4.1

[2016-02-09T07:34:15-05:00] WARN: [inet6] no ip address on venet0

resolving cookbooks for run list: ["unifiedpush"]

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:15-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:16-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:16-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:16-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

[2016-02-09T07:34:16-05:00] WARN: Cookbook 'local-mode-cache' is empty or
entirely chefignored at /opt/unifiedpush/embedded/cookbooks/local-mode-cache

Synchronizing Cookbooks:

  - package

  - runit

  - unifiedpush

Compiling Cookbooks...

Recipe: unifiedpush::default

  * directory[/etc/unifiedpush] action create (up to date)

/sbin/init: unrecognized option '--version'

  -.mount                                 loaded active mounted   /

[2016-02-09T07:34:16-05:00] WARN: Selected systemd because systemctl shows
.mount units

[2016-02-09T07:34:16-05:00] WARN: Cloning resource attributes for
directory[/etc/sysctl.d] from prior resource (CHEF-3694)

[2016-02-09T07:34:16-05:00] WARN: Previous directory[/etc/sysctl.d]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:22:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Current  directory[/etc/sysctl.d]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:22:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Cloning resource attributes for
file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] from prior
resource (CHEF-3694)

[2016-02-09T07:34:16-05:00] WARN: Previous
file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:27:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Current
file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:27:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Cloning resource attributes for
link[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] from prior
resource (CHEF-3694)

[2016-02-09T07:34:16-05:00] WARN: Previous
link[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:40:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Current
link[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:40:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Cloning resource attributes for
execute[sysctl] from prior resource (CHEF-3694)

[2016-02-09T07:34:16-05:00] WARN: Previous execute[sysctl]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:45:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Current  execute[sysctl]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:45:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Cloning resource attributes for
directory[/etc/sysctl.d] from prior resource (CHEF-3694)

[2016-02-09T07:34:16-05:00] WARN: Previous directory[/etc/sysctl.d]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:22:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Current  directory[/etc/sysctl.d]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:22:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Cloning resource attributes for
file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] from prior
resource (CHEF-3694)

[2016-02-09T07:34:16-05:00] WARN: Previous
file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:27:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Current
file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:27:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Cloning resource attributes for
link[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] from prior
resource (CHEF-3694)

[2016-02-09T07:34:16-05:00] WARN: Previous
link[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:40:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Current
link[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:40:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Cloning resource attributes for
execute[sysctl] from prior resource (CHEF-3694)

[2016-02-09T07:34:16-05:00] WARN: Previous execute[sysctl]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:45:in
`block in from_file'

[2016-02-09T07:34:16-05:00] WARN: Current  execute[sysctl]:
/opt/unifiedpush/embedded/cookbooks/cache/cookbooks/unifiedpush/definitions/sysctl.rb:45:in
`block in from_file'

  Converging 121 resources

  * directory[/etc/unifiedpush] action nothing (skipped due to action
:nothing)

  * directory[/opt/unifiedpush/embedded/etc] action create (up to date)

Recipe: unifiedpush::users

  * directory[/var/opt/unifiedpush] action create (up to date)

  * group[unifiedpush] action create (up to date)

  * user[unifiedpush] action create (up to date)

Recipe: runit::systemd

  * directory[/usr/lib/systemd/system] action create (up to date)

  * cookbook_file[/usr/lib/systemd/system/unifiedpush-runsvdir.service]
action create (up to date)

  *
file[/etc/systemd/system/default.target.wants/unifiedpush-runsvdir.service]
action delete (up to date)

  * execute[systemctl daemon-reload] action nothing (skipped due to action
:nothing)

  * execute[systemctl enable unifiedpush-runsvdir] action nothing (skipped
due to action :nothing)

  * execute[systemctl start unifiedpush-runsvdir] action nothing (skipped
due to action :nothing)

Recipe: unifiedpush::postgresql

  * group[unifiedpush-pgs] action create (up to date)

  * user[unifiedpush-pgs] action create (up to date)

  * directory[/var/opt/unifiedpush/postgresql] action create (up to date)

  * directory[/var/opt/unifiedpush/postgresql/data] action create (up to
date)

  * directory[/var/log/unifiedpush/postgresql] action create (up to date)

  * link[/var/opt/unifiedpush/postgresql/data] action create (skipped due
to not_if)

  * file[/var/opt/unifiedpush/postgresql/.profile] action create (up to
date)

  * directory[/etc/sysctl.d] action create (up to date)

  * file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] action
touch[2016-02-09T07:34:18-05:00] WARN: File
/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf managed by
file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] is really a
symlink. Managing the source file instead.

[2016-02-09T07:34:18-05:00] WARN: Disable this warning by setting
`manage_symlink_source true` on the resource

[2016-02-09T07:34:18-05:00] WARN: In a future Chef release,
'manage_symlink_source' will not be enabled by default


    - update utime on file
/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf

  * bash[add kernel.shmmax settings] action run (skipped due to not_if)

  * link[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] action
create (up to date)

  * execute[sysctl] action nothing (skipped due to action :nothing)

  * directory[/etc/sysctl.d] action create (up to date)

  * file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] action
touch[2016-02-09T07:34:18-05:00] WARN: File
/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf managed by
file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] is really a
symlink. Managing the source file instead.

[2016-02-09T07:34:18-05:00] WARN: Disable this warning by setting
`manage_symlink_source true` on the resource

[2016-02-09T07:34:18-05:00] WARN: In a future Chef release,
'manage_symlink_source' will not be enabled by default


    - update utime on file
/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf

  * bash[add kernel.shmall settings] action run (skipped due to not_if)

  * link[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] action
create (up to date)

  * execute[sysctl] action nothing (skipped due to action :nothing)

  * directory[/etc/sysctl.d] action create (up to date)

  * file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] action
touch[2016-02-09T07:34:18-05:00] WARN: File
/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf managed by
file[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] is really a
symlink. Managing the source file instead.

[2016-02-09T07:34:18-05:00] WARN: Disable this warning by setting
`manage_symlink_source true` on the resource

[2016-02-09T07:34:18-05:00] WARN: In a future Chef release,
'manage_symlink_source' will not be enabled by default


    - update utime on file
/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf

  * bash[add kernel.sem settings] action run

    - execute "bash"  "/tmp/chef-script20160209-4491-1x0ix17"

  * execute[sysctl] action run

    - execute cat /etc/sysctl.conf /etc/sysctl.d/*.conf  | sysctl -e -p -

  * link[/opt/unifiedpush/embedded/etc/90-omnibus-unifiedpush.conf] action
create (up to date)

  * execute[sysctl] action nothing (skipped due to action :nothing)

  * execute[/opt/unifiedpush/embedded/bin/initdb -D
/var/opt/unifiedpush/postgresql/data -E UTF8] action run (skipped due to
not_if)

  * template[/var/opt/unifiedpush/postgresql/data/postgresql.conf] action
create (up to date)

  * template[/var/opt/unifiedpush/postgresql/data/pg_hba.conf] action
create (up to date)

  * template[/var/opt/unifiedpush/postgresql/data/pg_ident.conf] action
create (up to date)

  * directory[/opt/unifiedpush/sv/postgresql] action create (up to date)

  * directory[/opt/unifiedpush/sv/postgresql/log] action create (up to date)

  * directory[/opt/unifiedpush/sv/postgresql/log/main] action create (up to
date)

  * template[/opt/unifiedpush/sv/postgresql/run] action create (up to date)

  * template[/opt/unifiedpush/sv/postgresql/log/run] action create (up to
date)

  * template[/var/log/unifiedpush/postgresql/config] action create (up to
date)

  * ruby_block[reload postgresql svlogd configuration] action nothing
(skipped due to action :nothing)

  * file[/opt/unifiedpush/sv/postgresql/down] action delete (up to date)

  * directory[/opt/unifiedpush/sv/postgresql/control] action create (up to
date)

  * template[/opt/unifiedpush/sv/postgresql/control/t] action create (up to
date)

  * link[/opt/unifiedpush/init/postgresql] action create (up to date)

  * link[/opt/unifiedpush/service/postgresql] action create (up to date)

  * ruby_block[supervise_postgresql_sleep] action run (skipped due to
not_if)

  * service[postgresql] action nothing (skipped due to action :nothing)

Recipe: unifiedpush::postgresql_database_setup

  * execute[create user unifiedpush_server for database unifiedpush_server]
action run (skipped due to not_if)

  * execute[create unifiedpush_server database] action run (skipped due to
not_if)

  * execute[create user unifiedpush_server for database keycloak_server]
action run (skipped due to not_if)

  * execute[create keycloak_server database] action run (skipped due to
not_if)

Recipe: unifiedpush::postgresql_database_schema

  * execute[initialize unifiedpush-server database] action nothing (skipped
due to action :nothing)

  * execute[initialize keycloak-server database] action nothing (skipped
due to action :nothing)

Recipe: unifiedpush::web-server

  * group[unifiedpush-www] action create (up to date)

  * user[unifiedpush-www] action create (up to date)

Recipe: unifiedpush::nginx

  * directory[/var/opt/unifiedpush/nginx] action create (up to date)

  * directory[/var/opt/unifiedpush/nginx/conf] action create (up to date)

  * directory[/var/log/unifiedpush/nginx] action create (up to date)

  * link[/var/opt/unifiedpush/nginx/logs] action create (up to date)

  * template[/var/opt/unifiedpush/nginx/conf/unifiedpush-http.conf] action
create (up to date)

  * template[/var/opt/unifiedpush/nginx/conf/nginx.conf] action create (up
to date)

  * directory[/opt/unifiedpush/sv/nginx] action create (up to date)

  * directory[/opt/unifiedpush/sv/nginx/log] action create (up to date)

  * directory[/opt/unifiedpush/sv/nginx/log/main] action create (up to date)

  * template[/opt/unifiedpush/sv/nginx/run] action create (up to date)

  * template[/opt/unifiedpush/sv/nginx/log/run] action create (up to date)

  * template[/var/log/unifiedpush/nginx/config] action create (up to date)

  * ruby_block[reload nginx svlogd configuration] action nothing (skipped
due to action :nothing)

  * file[/opt/unifiedpush/sv/nginx/down] action delete (up to date)

  * link[/opt/unifiedpush/init/nginx] action create (up to date)

  * link[/opt/unifiedpush/service/nginx] action create (up to date)

  * ruby_block[supervise_nginx_sleep] action run (skipped due to not_if)

  * service[nginx] action nothing (skipped due to action :nothing)

Recipe: unifiedpush::logrotate

  * directory[/var/opt/unifiedpush/logrotate] action create (up to date)

  * directory[/var/opt/unifiedpush/logrotate/logrotate.d] action create (up
to date)

  * directory[/var/log/unifiedpush/logrotate] action create (up to date)

  * template[/var/opt/unifiedpush/logrotate/logrotate.conf] action create
(up to date)

  * template[/var/opt/unifiedpush/logrotate/logrotate.d/nginx] action
create (up to date)

  * template[/var/opt/unifiedpush/logrotate/logrotate.d/unifiedpush-server]
action create (up to date)

  * directory[/opt/unifiedpush/sv/logrotate] action create (up to date)

  * directory[/opt/unifiedpush/sv/logrotate/log] action create (up to date)

  * directory[/opt/unifiedpush/sv/logrotate/log/main] action create (up to
date)

  * template[/opt/unifiedpush/sv/logrotate/run] action create (up to date)

  * template[/opt/unifiedpush/sv/logrotate/log/run] action create (up to
date)

  * template[/var/log/unifiedpush/logrotate/config] action create (up to
date)

  * ruby_block[reload logrotate svlogd configuration] action nothing
(skipped due to action :nothing)

  * file[/opt/unifiedpush/sv/logrotate/down] action delete (up to date)

  * link[/opt/unifiedpush/init/logrotate] action create (up to date)

  * link[/opt/unifiedpush/service/logrotate] action create (up to date)

  * ruby_block[supervise_logrotate_sleep] action run (skipped due to not_if)

  * service[logrotate] action nothing (skipped due to action :nothing)

Recipe: unifiedpush::unifiedpush-server

  * directory[/var/opt/unifiedpush/unifiedpush-server] action create (up to
date)

  * directory[/var/log/unifiedpush/unifiedpush-server] action create (up to
date)

  * directory[/var/opt/unifiedpush/unifiedpush-server/documents] action
create (up to date)

  * directory[/var/opt/unifiedpush/unifiedpush-server/uploads] action
create (up to date)

  * execute[extract_wildfly] action run (skipped due to not_if)

  * execute[chown-unifiedpush-server] action run

    - execute chown -R unifiedpush:root
/var/opt/unifiedpush/unifiedpush-server

Recipe: unifiedpush::unifiedpush-server-wildfly-conf

  *
directory[/var/opt/unifiedpush/unifiedpush-server/modules/org/postgresql/main]
action create (up to date)

  * template[/var/opt/unifiedpush/unifiedpush-server/bin/standalone.conf]
action create (up to date)

  *
template[/var/opt/unifiedpush/unifiedpush-server/modules/org/postgresql/main/module.xml]
action create (up to date)

  * remote_file[Copy postgres driver file] action create (up to date)

  *
template[/var/opt/unifiedpush/unifiedpush-server/standalone/configuration/standalone-full.xml]
action create (up to date)

  *
link[/var/opt/unifiedpush/unifiedpush-server/standalone/deployments/unifiedpush-server.war]
action create (up to date)

  *
link[/var/opt/unifiedpush/unifiedpush-server/standalone/deployments/auth-server.war]
action create (up to date)

Recipe: unifiedpush::unifiedpush-server

  *
template[/var/opt/unifiedpush/unifiedpush-server/standalone/configuration/unifiedpush-server.properties]
action create (up to date)

  * directory[/opt/unifiedpush/sv/unifiedpush-server] action create (up to
date)

  * directory[/opt/unifiedpush/sv/unifiedpush-server/log] action create (up
to date)

  * directory[/opt/unifiedpush/sv/unifiedpush-server/log/main] action
create (up to date)

  * template[/opt/unifiedpush/sv/unifiedpush-server/run] action create (up
to date)

  * template[/opt/unifiedpush/sv/unifiedpush-server/log/run] action create
(up to date)

  * template[/var/log/unifiedpush/unifiedpush-server/config] action create
(up to date)

  * ruby_block[reload unifiedpush-server svlogd configuration] action
nothing (skipped due to action :nothing)

  * file[/opt/unifiedpush/sv/unifiedpush-server/down] action delete (up to
date)

  * link[/opt/unifiedpush/init/unifiedpush-server] action create (up to
date)

  * link[/opt/unifiedpush/service/unifiedpush-server] action create (up to
date)

  * ruby_block[supervise_unifiedpush-server_sleep] action run (skipped due
to not_if)

  * service[unifiedpush-server] action nothing (skipped due to action
:nothing)


Running handlers:

Running handlers complete

Chef Client finished, 6/93 resources updated in 6.663070131 seconds

unifiedpush Reconfigured!

2016-02-09 8:00 GMT+01:00 yaniv-cb4 <notifications@github.com>:

**Comment by yaniv-cb4** [comment]
Thanks for your time and effort!
Service is now available under http://s3.yourapplicationbuilder.eu/unifiedpush-server

I've changed one configuration option under /etc/unifiedpush/unifiedpush.rb, deleted previous installation data (/var/opt/unifiedpush), and reconfigure (unifiedpush-ctl reconfigure).
```
Change
# postgresql['trust_auth_cidr_addresses'] = ['localhost']
To
postgresql['trust_auth_cidr_addresses'] = ['localhost','127.0.0.1/32']
```

I believe this error occur when /etc/hosts entry for localhost is:
```
127.0.0.1 localhost.localdomain localhost localhost4.localdomain4 localhost4
and not 
127.0.0.1 localhost localhost.localdomain localhost4.localdomain4 localhost4
```

\Regards

**Comment by rogeroffer** [comment]
Hi,

Is it also possible tu run unified push server in an excisiting web server?

Greetings roger

2016-02-09 15:05 GMT+02:00 yaniv-cb4 <notifications@github.com>:

**Comment by yaniv-cb4** [comment]
You can read https://github.com/C-B4/unifiedpush-server/wiki/Unifiedpush-Installation for our recommendation.

**Comment by rogeroffer** [comment]
Hi Yaniv,

Did the packages of the unified push server moved? Can not find them anymore

Greetings Roger

2016-02-29 11:36 GMT+02:00 yaniv-cb4 <notifications@github.com>:

**Comment by yaniv-cb4** [comment]
Yes, sorry for any inconvenience this may have caused. you can build from sources.

**Comment by yaniv-cb4** [comment]
Packages are available at http://ups.c-b4.com/ups/packages/
sorry for any inconvenience this may have caused.
